// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Squadmakers.Infraestructure.Models;

public partial class Chiste
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Titulo { get; set; }

    [Required]
    public string Cuerpo { get; set; }

    [Required]
    [StringLength(255)]
    public string Autor { get; set; }

    public Guid UsuarioId { get; set; }

    [ForeignKey("UsuarioId")]
    [InverseProperty("Chistes")]
    public virtual Usuario Usuario { get; set; }

    [ForeignKey("ChisteId")]
    [InverseProperty("Chistes")]
    public virtual ICollection<Tematica> Tematicas { get; set; } = new List<Tematica>();
}