// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Squadmakers.Infraestructure.Models;

[Table("Joke")]
public partial class Joke
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [Unicode(false)]
    public string Descripcion { get; set; }
}